version: 2
updates:
  # Maintain dependencies for pip
  - package-ecosystem: "pip" 
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    reviewers:
      - "lizzcondrey"
    labels:
      - "security"
      - "dependencies"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "lizzcondrey"
    labels:
      - "security"
      - "dependencies"
